% -------------------------------------------------------------------
%  Generated by MATLAB on 17-Nov-2022 13:53:12
%  MATLAB version: 9.9.0.1538559 (R2020b) Update 3
% -------------------------------------------------------------------
                                            

Configuration = Simulink.ConfigSet;
Configuration.set_param('Name', 'Configuration');
Configuration.set_param('Description', '');
Configuration.set_param('SystemTargetFile', 'ert.tlc');
Configuration.set_param('HardwareBoard', 'None');
Configuration.set_param('TargetLang', 'C++');
Configuration.set_param('CodeInterfacePackaging', 'Reusable function');
Configuration.set_param('GenerateAllocFcn', 'on');
Configuration.set_param('Solver', 'FixedStepDiscrete');
Configuration.set_param('StartTime', '0');
Configuration.set_param('StopTime', '40');
Configuration.set_param('SampleTimeConstraint', 'Unconstrained');
Configuration.set_param('SolverType', 'Fixed-step');
Configuration.set_param('SolverName', 'FixedStepDiscrete');
Configuration.set_param('ConcurrentTasks', 'off');
Configuration.set_param('FixedStep', 'Ts');
Configuration.set_param('EnableMultiTasking', 'off');
Configuration.set_param('PositivePriorityOrder', 'off');
Configuration.set_param('AutoInsertRateTranBlk', 'off');
Configuration.set_param('Decimation', '1');
Configuration.set_param('LoadExternalInput', 'off');
Configuration.set_param('SaveFinalState', 'off');
Configuration.set_param('LoadInitialState', 'off');
Configuration.set_param('LimitDataPoints', 'off');
Configuration.set_param('SaveFormat', 'Dataset');
Configuration.set_param('SaveOutput', 'off');
Configuration.set_param('SaveState', 'off');
Configuration.set_param('SignalLogging', 'on');
Configuration.set_param('DSMLogging', 'off');
Configuration.set_param('InspectSignalLogs', 'off');
Configuration.set_param('SaveTime', 'off');
Configuration.set_param('ReturnWorkspaceOutputs', 'off');
Configuration.set_param('SignalLoggingName', 'logsout');
Configuration.set_param('LoggingToFile', 'off');
Configuration.set_param('DatasetSignalFormat', 'timeseries');
Configuration.set_param('BlockReduction', 'on');
Configuration.set_param('BooleanDataType', 'on');
Configuration.set_param('ConditionallyExecuteInputs', 'on');
Configuration.set_param('DefaultParameterBehavior', 'Inlined');
Configuration.set_param('UseDivisionForNetSlopeComputation', 'off');
Configuration.set_param('GainParamInheritBuiltInType', 'off');
Configuration.set_param('UseFloatMulNetSlope', 'off');
Configuration.set_param('DefaultUnderspecifiedDataType', 'double');
Configuration.set_param('UseSpecifiedMinMax', 'off');
Configuration.set_param('InlineInvariantSignals', 'off');
Configuration.set_param('OptimizationCustomize', 'off');
Configuration.set_param('OptimizationPriority', 'Balanced');
Configuration.set_param('OptimizationLevel', 'level2');
Configuration.set_param('DataBitsets', 'off');
Configuration.set_param('StateBitsets', 'off');
Configuration.set_param('LocalBlockOutputs', 'on');
Configuration.set_param('EnableMemcpy', 'on');
Configuration.set_param('ExpressionFolding', 'on');
Configuration.set_param('BufferReuse', 'on');
Configuration.set_param('OptimizeBlockIOStorage', 'on');
Configuration.set_param('AdvancedOptControl', '');
Configuration.set_param('BitwiseOrLogicalOp', 'Same as modeled');
Configuration.set_param('MemcpyThreshold', 64);
Configuration.set_param('PassReuseOutputArgsAs', 'Individual arguments');
Configuration.set_param('PassReuseOutputArgsThreshold', 12);
Configuration.set_param('RollThreshold', 5);
Configuration.set_param('ActiveStateOutputEnumStorageType', ['Native In' ...
                         'teger']);
Configuration.set_param('ZeroExternalMemoryAtStartup', 'off');
Configuration.set_param('ZeroInternalMemoryAtStartup', 'on');
Configuration.set_param('InitFltsAndDblsToZero', 'off');
Configuration.set_param('NoFixptDivByZeroProtection', 'off');
Configuration.set_param('EfficientFloat2IntCast', 'on');
Configuration.set_param('EfficientMapNaN2IntZero', 'on');
Configuration.set_param('LifeSpan', 'auto');
Configuration.set_param('MaxStackSize', 'Inherit from target');
Configuration.set_param('BufferReusableBoundary', 'on');
Configuration.set_param('SimCompilerOptimization', 'off');
Configuration.set_param('AccelVerboseBuild', 'off');
Configuration.set_param('UseRowMajorAlgorithm', 'off');
Configuration.set_param('LabelGuidedReuse', 'off');
Configuration.set_param('DenormalBehavior', 'GradualUnderflow');
Configuration.set_param('EfficientTunableParamExpr', 'on');
Configuration.set_param('RTPrefix', 'error');
Configuration.set_param('ConsistencyChecking', 'none');
Configuration.set_param('ArrayBoundsChecking', 'none');
Configuration.set_param('SignalInfNanChecking', 'none');
Configuration.set_param('StringTruncationChecking', 'error');
Configuration.set_param('SignalRangeChecking', 'none');
Configuration.set_param('ReadBeforeWriteMsg', 'UseLocalSettings');
Configuration.set_param('WriteAfterWriteMsg', 'UseLocalSettings');
Configuration.set_param('WriteAfterReadMsg', 'UseLocalSettings');
Configuration.set_param('AlgebraicLoopMsg', 'warning');
Configuration.set_param('ArtificialAlgebraicLoopMsg', 'warning');
Configuration.set_param('SaveWithDisabledLinksMsg', 'warning');
Configuration.set_param('SaveWithParameterizedLinksMsg', 'warning');
Configuration.set_param('UnderspecifiedInitializationDetection', ['Simp' ...
                         'lified']);
Configuration.set_param('MergeDetectMultiDrivingBlocksExec', 'error');
Configuration.set_param('SignalResolutionControl', 'UseLocalSettings');
Configuration.set_param('BlockPriorityViolationMsg', 'warning');
Configuration.set_param('MinStepSizeMsg', 'warning');
Configuration.set_param('TimeAdjustmentMsg', 'none');
Configuration.set_param('MaxConsecutiveZCsMsg', 'error');
Configuration.set_param('MaskedZcDiagnostic', 'warning');
Configuration.set_param('IgnoredZcDiagnostic', 'warning');
Configuration.set_param('SolverPrmCheckMsg', 'none');
Configuration.set_param('InheritedTsInSrcMsg', 'warning');
Configuration.set_param('MultiTaskDSMMsg', 'error');
Configuration.set_param('MultiTaskCondExecSysMsg', 'error');
Configuration.set_param('MultiTaskRateTransMsg', 'error');
Configuration.set_param('SingleTaskRateTransMsg', 'none');
Configuration.set_param('TasksWithSamePriorityMsg', 'warning');
Configuration.set_param('SigSpecEnsureSampleTimeMsg', 'warning');
Configuration.set_param('CheckMatrixSingularityMsg', 'none');
Configuration.set_param('IntegerOverflowMsg', 'warning');
Configuration.set_param('Int32ToFloatConvMsg', 'warning');
Configuration.set_param('ParameterDowncastMsg', 'error');
Configuration.set_param('ParameterOverflowMsg', 'error');
Configuration.set_param('ParameterUnderflowMsg', 'none');
Configuration.set_param('ParameterPrecisionLossMsg', 'warning');
Configuration.set_param('ParameterTunabilityLossMsg', 'error');
Configuration.set_param('FixptConstUnderflowMsg', 'none');
Configuration.set_param('FixptConstOverflowMsg', 'none');
Configuration.set_param('FixptConstPrecisionLossMsg', 'none');
Configuration.set_param('UnderSpecifiedDataTypeMsg', 'none');
Configuration.set_param('UnnecessaryDatatypeConvMsg', 'none');
Configuration.set_param('VectorMatrixConversionMsg', 'none');
Configuration.set_param('FcnCallInpInsideContextMsg', 'error');
Configuration.set_param('SignalLabelMismatchMsg', 'none');
Configuration.set_param('UnconnectedInputMsg', 'warning');
Configuration.set_param('UnconnectedOutputMsg', 'warning');
Configuration.set_param('UnconnectedLineMsg', 'warning');
Configuration.set_param('SFcnCompatibilityMsg', 'none');
Configuration.set_param('FrameProcessingCompatibilityMsg', 'error');
Configuration.set_param('UniqueDataStoreMsg', 'none');
Configuration.set_param('BusObjectLabelMismatch', 'warning');
Configuration.set_param('RootOutportRequireBusObject', 'warning');
Configuration.set_param('AssertControl', 'UseLocalSettings');
Configuration.set_param('AllowSymbolicDim', 'on');
Configuration.set_param('ModelReferenceIOMsg', 'none');
Configuration.set_param('ModelReferenceVersionMismatchMessage', 'none');
Configuration.set_param('ModelReferenceIOMismatchMessage', 'none');
Configuration.set_param('UnknownTsInhSupMsg', 'warning');
Configuration.set_param('ModelReferenceDataLoggingMessage', 'warning');
Configuration.set_param('ModelReferenceNoExplicitFinalValueMsg', 'none');
Configuration.set_param('ModelReferenceSymbolNameMessage', 'warning');
Configuration.set_param('ModelReferenceExtraNoncontSigs', 'error');
Configuration.set_param('StateNameClashWarn', 'none');
Configuration.set_param('OperatingPointInterfaceChecksumMismatchMsg', ['w' ...
                         'arning']);
Configuration.set_param('NonCurrentReleaseOperatingPointMsg', 'error');
Configuration.set_param('PregeneratedLibrarySubsystemCodeDiagnostic', ['w' ...
                         'arning']);
Configuration.set_param('InitInArrayFormatMsg', 'warning');
Configuration.set_param('StrictBusMsg', 'ErrorLevel1');
Configuration.set_param('BusNameAdapt', 'WarnAndRepair');
Configuration.set_param('NonBusSignalsTreatedAsBus', 'none');
Configuration.set_param('SFUnusedDataAndEventsDiag', 'warning');
Configuration.set_param('SFUnexpectedBacktrackingDiag', 'error');
Configuration.set_param('SFInvalidInputDataAccessInChartInitDiag', ['wa' ...
                         'rning']);
Configuration.set_param('SFNoUnconditionalDefaultTransitionDiag', ['err' ...
                         'or']);
Configuration.set_param('SFTransitionOutsideNaturalParentDiag', ['warni' ...
                         'ng']);
Configuration.set_param('SFUnreachableExecutionPathDiag', 'warning');
Configuration.set_param('SFUndirectedBroadcastEventsDiag', 'warning');
Configuration.set_param('SFTransitionActionBeforeConditionDiag', ['warn' ...
                         'ing']);
Configuration.set_param('SFOutputUsedAsStateInMooreChartDiag', 'error');
Configuration.set_param('SFTemporalDelaySmallerThanSampleTimeDiag', ['w' ...
                         'arning']);
Configuration.set_param('SFSelfTransitionDiag', 'warning');
Configuration.set_param('SFExecutionAtInitializationDiag', 'warning');
Configuration.set_param('SFMachineParentedDataDiag', 'warning');
Configuration.set_param('IntegerSaturationMsg', 'warning');
Configuration.set_param('AllowedUnitSystems', 'all');
Configuration.set_param('UnitsInconsistencyMsg', 'warning');
Configuration.set_param('AllowAutomaticUnitConversions', 'on');
Configuration.set_param('RCSCRenamedMsg', 'warning');
Configuration.set_param('RCSCObservableMsg', 'warning');
Configuration.set_param('ForceCombineOutputUpdateInSim', 'off');
Configuration.set_param('UnderSpecifiedDimensionMsg', 'none');
Configuration.set_param('DebugExecutionForFMUViaOutOfProcess', 'off');
Configuration.set_param('ArithmeticOperatorsInVariantConditions', ['war' ...
                         'ning']);
Configuration.set_param('VariantConditionMismatch', 'none');
Configuration.set_param('ProdHWDeviceType', 'Intel->x86-64 (Linux 64)');
Configuration.set_param('ProdLongLongMode', 'on');
Configuration.set_param('ProdEqTarget', 'on');
Configuration.set_param('TargetPreprocMaxBitsSint', 32);
Configuration.set_param('TargetPreprocMaxBitsUint', 32);
Configuration.set_param('HardwareBoardFeatureSet', 'EmbeddedCoderHSP');
Configuration.set_param('UpdateModelReferenceTargets', ['IfOutOfDateOrS' ...
                         'tructuralChange']);
Configuration.set_param('EnableRefExpFcnMdlSchedulingChecks', 'on');
Configuration.set_param('EnableParallelModelReferenceBuilds', 'off');
Configuration.set_param('ParallelModelReferenceErrorOnInvalidPool', ['o' ...
                         'n']);
Configuration.set_param('ModelReferenceNumInstancesAllowed', 'Multi');
Configuration.set_param('PropagateVarSize', ['Infer from blocks in mode' ...
                         'l']);
Configuration.set_param('ModelDependencies', '');
Configuration.set_param('ModelReferencePassRootInputsByReference', 'on');
Configuration.set_param('ModelReferenceMinAlgLoopOccurrences', 'off');
Configuration.set_param('PropagateSignalLabelsOutOfModel', 'on');
Configuration.set_param('SupportModelReferenceSimTargetCustomCode', ['o' ...
                         'ff']);
Configuration.set_param('SimCustomSourceCode', '');
Configuration.set_param('SimCustomHeaderCode', '');
Configuration.set_param('SimCustomInitializer', '');
Configuration.set_param('SimCustomTerminator', '');
Configuration.set_param('SimReservedNameArray', []);
Configuration.set_param('SimUserSources', '');
Configuration.set_param('SimUserIncludeDirs', '');
Configuration.set_param('SimUserLibraries', '');
Configuration.set_param('SimUserDefines', '');
Configuration.set_param('SFSimEnableDebug', 'off');
Configuration.set_param('SFSimEcho', 'on');
Configuration.set_param('SimCtrlC', 'on');
Configuration.set_param('SimIntegrity', 'on');
Configuration.set_param('SimParseCustomCode', 'on');
Configuration.set_param('SimAnalyzeCustomCode', 'off');
Configuration.set_param('SimGenImportedTypeDefs', 'off');
Configuration.set_param('CompileTimeRecursionLimit', 50);
Configuration.set_param('EnableRuntimeRecursion', 'on');
Configuration.set_param('MATLABDynamicMemAlloc', 'off');
Configuration.set_param('CustomCodeFunctionArrayLayout', []);
Configuration.set_param('DefaultCustomCodeFunctionArrayLayout', ['NotSp' ...
                         'ecified']);
Configuration.set_param('CustomCodeUndefinedFunction', ['UseInterfaceOn' ...
                         'ly']);
Configuration.set_param('CustomCodeGlobalsAsFunctionIO', 'off');
Configuration.set_param('GPUAcceleration', 'off');
Configuration.set_param('SimTargetLang', 'C');
Configuration.set_param('GenerateGPUCode', 'None');
Configuration.set_param('RemoveResetFunc', 'on');
Configuration.set_param('ExistingSharedCode', '');
Configuration.set_param('TLCOptions', '');
Configuration.set_param('GenCodeOnly', 'on');
Configuration.set_param('PackageGeneratedCodeAndArtifacts', 'on');
Configuration.set_param('PackageName', '');
Configuration.set_param('PostCodeGenCommand', 'packNGo(buildInfo);');
Configuration.set_param('GenerateReport', 'on');
Configuration.set_param('RTWVerbose', 'on');
Configuration.set_param('RetainRTWFile', 'off');
Configuration.set_param('ProfileTLC', 'off');
Configuration.set_param('TLCDebug', 'off');
Configuration.set_param('TLCCoverage', 'off');
Configuration.set_param('TLCAssert', 'off');
Configuration.set_param('RTWUseSimCustomCode', 'off');
Configuration.set_param('CustomSourceCode', ['void *GETMMIFCN(MODEL)(vo' ...
                         'id *rtm)', char(10), '{', char(10), '  return' ...
                         ' (void *)&((static_cast<TSTRUCTNAME(MODEL) *>' ...
                         '(rtm)->DataMapInfo).mmi);', char(10), '}']);
Configuration.set_param('CustomHeaderCode', ['#ifndef SCDMACROS', char(10), '' ...
                         '#define SCDMACROS', char(10), '  #define UTST' ...
                         'RUCTNAME(NAME)             RT_MODEL_##NAME##_' ...
                         'T', char(10), '  #define TSTRUCTNAME(NAME)   ' ...
                         '           UTSTRUCTNAME(NAME)', char(10), '  ' ...
                         '#define UGETMMIFCN(NAME)               NAME##' ...
                         '_GetCAPImmi', char(10), '  #define GETMMIFCN(' ...
                         'NAME)                UGETMMIFCN(NAME)', char(10), '' ...
                         '#endif', char(10), '', char(10), '#ifdef __cp' ...
                         'lusplus', char(10), '', char(10), 'extern "C"' ...
                         ' {', char(10), '', char(10), '#endif', char(10), '' ...
                         '', char(10), '  void *GETMMIFCN(MODEL)(void *' ...
                         'rtm);', char(10), '', char(10), '#ifdef __cpl' ...
                         'usplus', char(10), '', char(10), '}', char(10), '' ...
                         '#endif']);
Configuration.set_param('CustomInclude', '');
Configuration.set_param('CustomSource', '');
Configuration.set_param('CustomLibrary', '');
Configuration.set_param('CustomDefine', '');
Configuration.set_param('CustomBLASCallback', '');
Configuration.set_param('CustomLAPACKCallback', '');
Configuration.set_param('CustomFFTCallback', '');
Configuration.set_param('CustomInitializer', '');
Configuration.set_param('CustomTerminator', '');
Configuration.set_param('Toolchain', ['GNU gcc/g++ | gmake (64-bit Linu' ...
                         'x)']);
Configuration.set_param('BuildConfiguration', 'Faster Runs');
Configuration.set_param('IncludeHyperlinkInReport', 'off');
Configuration.set_param('LaunchReport', 'on');
Configuration.set_param('PortableWordSizes', 'off');
Configuration.set_param('CreateSILPILBlock', 'None');
Configuration.set_param('CodeExecutionProfiling', 'off');
Configuration.set_param('CodeProfilingInstrumentation', 'off');
Configuration.set_param('SILDebugging', 'off');
Configuration.set_param('GenerateTraceInfo', 'off');
Configuration.set_param('GenerateTraceReport', 'off');
Configuration.set_param('GenerateTraceReportSl', 'off');
Configuration.set_param('GenerateTraceReportSf', 'off');
Configuration.set_param('GenerateTraceReportEml', 'off');
Configuration.set_param('GenerateWebview', 'off');
Configuration.set_param('GenerateCodeMetricsReport', 'off');
Configuration.set_param('GenerateCodeReplacementReport', 'off');
saveVarsTmp{1} = cell(1, 1);
saveVarsTmp{1}{1} = 'Execution efficiency';
Configuration.set_param('ObjectivePriorities', saveVarsTmp{1});
Configuration.set_param('CheckMdlBeforeBuild', 'Off');
Configuration.set_param('DLTargetLibrary', 'none');
Configuration.set_param('GenerateComments', 'on');
Configuration.set_param('ForceParamTrailComments', 'on');
Configuration.set_param('CommentStyle', 'Auto');
Configuration.set_param('IgnoreCustomStorageClasses', 'off');
Configuration.set_param('IgnoreTestpoints', 'off');
Configuration.set_param('MaxIdLength', 62);
Configuration.set_param('ShowEliminatedStatement', 'on');
Configuration.set_param('OperatorAnnotations', 'on');
Configuration.set_param('SimulinkDataObjDesc', 'on');
Configuration.set_param('SFDataObjDesc', 'on');
Configuration.set_param('MATLABFcnDesc', 'off');
Configuration.set_param('MangleLength', 1);
Configuration.set_param('SharedChecksumLength', 8);
Configuration.set_param('CustomSymbolStrGlobalVar', '$R$N$M');
Configuration.set_param('CustomSymbolStrType', '$N$R$M_T');
Configuration.set_param('CustomSymbolStrField', '$N$M');
Configuration.set_param('CustomSymbolStrFcn', '$R$N$M$F');
Configuration.set_param('CustomSymbolStrFcnArg', 'rt$I$N$M');
Configuration.set_param('CustomSymbolStrBlkIO', 'rtb_$N$M');
Configuration.set_param('CustomSymbolStrTmpVar', '$N$M');
Configuration.set_param('CustomSymbolStrMacro', '$R$N$M');
Configuration.set_param('CustomSymbolStrUtil', '$N$C');
Configuration.set_param('CustomSymbolStrEmxType', 'emxArray_$M$N');
Configuration.set_param('CustomSymbolStrEmxFcn', 'emx$M$N');
Configuration.set_param('CustomUserTokenString', '');
Configuration.set_param('EnableCustomComments', 'off');
Configuration.set_param('DefineNamingRule', 'None');
Configuration.set_param('ParamNamingRule', 'None');
Configuration.set_param('SignalNamingRule', 'None');
Configuration.set_param('InsertBlockDesc', 'on');
Configuration.set_param('InsertPolySpaceComments', 'off');
Configuration.set_param('SimulinkBlockComments', 'on');
Configuration.set_param('StateflowObjectComments', 'off');
Configuration.set_param('BlockCommentType', 'BlockPathComment');
Configuration.set_param('MATLABSourceComments', 'off');
Configuration.set_param('InternalIdentifier', 'Shortened');
Configuration.set_param('InlinedPrmAccess', 'Macros');
Configuration.set_param('ReqsInCode', 'off');
Configuration.set_param('UseSimReservedNames', 'off');
Configuration.set_param('ReservedNameArray', []);
Configuration.set_param('EnumMemberNameClash', 'error');
Configuration.set_param('TargetLibSuffix', '');
Configuration.set_param('TargetPreCompLibLocation', '');
Configuration.set_param('TargetLangStandard', 'C++03 (ISO)');
Configuration.set_param('CodeReplacementLibrary', 'None');
Configuration.set_param('UtilityFuncGeneration', 'Auto');
Configuration.set_param('MultiwordTypeDef', 'System defined');
Configuration.set_param('DynamicStringBufferSize', 256);
Configuration.set_param('GenerateFullHeader', 'on');
Configuration.set_param('InferredTypesCompatibility', 'off');
Configuration.set_param('GenerateSampleERTMain', 'off');
Configuration.set_param('IncludeMdlTerminateFcn', 'on');
Configuration.set_param('GRTInterface', 'off');
Configuration.set_param('CombineOutputUpdateFcns', 'on');
Configuration.set_param('CombineSignalStateStructs', 'off');
Configuration.set_param('MatFileLogging', 'off');
Configuration.set_param('SuppressErrorStatus', 'off');
Configuration.set_param('IncludeFileDelimiter', 'Auto');
Configuration.set_param('ERTCustomFileBanners', 'on');
Configuration.set_param('SupportAbsoluteTime', 'on');
Configuration.set_param('PurelyIntegerCode', 'off');
Configuration.set_param('SupportNonFinite', 'off');
Configuration.set_param('SupportComplex', 'on');
Configuration.set_param('SupportContinuousTime', 'off');
Configuration.set_param('SupportNonInlinedSFcns', 'off');
Configuration.set_param('RemoveDisableFunc', 'off');
Configuration.set_param('SupportVariableSizeSignals', 'off');
Configuration.set_param('ParenthesesLevel', 'Nominal');
Configuration.set_param('CastingMode', 'Nominal');
Configuration.set_param('ArrayLayout', 'Column-major');
Configuration.set_param('LUTObjectStructOrderExplicitValues', ['Size,Br' ...
                         'eakpoints,Table']);
Configuration.set_param('LUTObjectStructOrderEvenSpacing', ['Size,Break' ...
                         'points,Table']);
Configuration.set_param('ERTHeaderFileRootName', '$R$E');
Configuration.set_param('ERTSourceFileRootName', '$R$E');
Configuration.set_param('ERTFilePackagingFormat', 'CompactWithDataFile');
Configuration.set_param('ERTDataFileRootName', '$R_data');
Configuration.set_param('GlobalDataDefinition', 'InSeparateSourceFile');
Configuration.set_param('GlobalDataReference', 'InSeparateHeaderFile');
Configuration.set_param('ExtMode', 'off');
Configuration.set_param('ExtModeTransport', 0);
Configuration.set_param('ExtModeMexFile', 'ext_comm');
Configuration.set_param('ExtModeStaticAlloc', 'off');
Configuration.set_param('MemSecPackage', '--- None ---');
Configuration.set_param('MemSecFuncSharedUtil', 'Default');
Configuration.set_param('MemSecFuncInitTerm', 'Default');
Configuration.set_param('MemSecFuncExecute', 'Default');
Configuration.set_param('MemSecDataParameters', 'Default');
Configuration.set_param('MemSecDataInternal', 'Default');
Configuration.set_param('MemSecDataIO', 'Default');
Configuration.set_param('MemSecDataConstants', 'Default');
Configuration.set_param('EnableUserReplacementTypes', 'off');
Configuration.set_param('ConvertIfToSwitch', 'on');
Configuration.set_param('DataDefinitionFile', 'global.c');
Configuration.set_param('DataReferenceFile', 'global.h');
Configuration.set_param('ERTCustomFileTemplate', ['example_file_process' ...
                         '.tlc']);
Configuration.set_param('ERTDataHdrFileTemplate', ['ert_code_template.c' ...
                         'gt']);
Configuration.set_param('ERTDataSrcFileTemplate', ['ert_code_template.c' ...
                         'gt']);
Configuration.set_param('ERTHdrFileBannerTemplate', ['ert_code_template' ...
                         '.cgt']);
Configuration.set_param('ERTSrcFileBannerTemplate', ['ert_code_template' ...
                         '.cgt']);
Configuration.set_param('EnableDataOwnership', 'off');
Configuration.set_param('ExtModeIntrfLevel', 'Level1');
Configuration.set_param('ExtModeMexArgs', '');
Configuration.set_param('ExtModeTesting', 'off');
Configuration.set_param('GenerateASAP2', 'off');
Configuration.set_param('IndentSize', '2');
Configuration.set_param('IndentStyle', 'K&R');
Configuration.set_param('NewlineStyle', 'Default');
Configuration.set_param('MaxLineWidth', 80);
Configuration.set_param('MultiInstanceErrorCode', 'Error');
Configuration.set_param('ParamTuneLevel', 10);
Configuration.set_param('EnableSignedLeftShifts', 'on');
Configuration.set_param('EnableSignedRightShifts', 'on');
Configuration.set_param('PreserveExpressionOrder', 'off');
Configuration.set_param('PreserveExternInFcnDecls', 'on');
Configuration.set_param('PreserveStaticInFcnDecls', 'on');
Configuration.set_param('PreserveIfCondition', 'off');
Configuration.set_param('RTWCAPIParams', 'on');
Configuration.set_param('RTWCAPIRootIO', 'on');
Configuration.set_param('RTWCAPISignals', 'off');
Configuration.set_param('RTWCAPIStates', 'off');
Configuration.set_param('RootIOFormat', 'Part of model data structure');
Configuration.set_param('SignalDisplayLevel', 10);
Configuration.set_param('SuppressUnreachableDefaultCases', 'on');
Configuration.set_param('BooleanTrueId', 'true');
Configuration.set_param('BooleanFalseId', 'false');
Configuration.set_param('MaxIdInt32', 'MAX_int32_T');
Configuration.set_param('MinIdInt32', 'MIN_int32_T');
Configuration.set_param('MaxIdUint32', 'MAX_uint32_T');
Configuration.set_param('MaxIdInt16', 'MAX_int16_T');
Configuration.set_param('MinIdInt16', 'MIN_int16_T');
Configuration.set_param('MaxIdUint16', 'MAX_uint16_T');
Configuration.set_param('MaxIdInt8', 'MAX_int8_T');
Configuration.set_param('MinIdInt8', 'MIN_int8_T');
Configuration.set_param('MaxIdUint8', 'MAX_uint8_T');
Configuration.set_param('MaxIdInt64', 'MAX_int64_T');
Configuration.set_param('MinIdInt64', 'MIN_int64_T');
Configuration.set_param('MaxIdUint64', 'MAX_uint64_T');
Configuration.set_param('TypeLimitIdReplacementHeaderFile', '');
Configuration.set_param('DSAsUniqueAccess', 'off');
Configuration.set_param('CovModelRefEnable', 'off');
Configuration.set_param('RecordCoverage', 'off');
Configuration.set_param('CovEnable', 'off');
clear saveVarsTmp;

